// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCqRe4EaS_DgDokP1QQUYmynj624_p7ow',
    appId: '1:1001893276480:android:1b313b4b89ee0d8628a8a5',
    messagingSenderId: '1001893276480',
    projectId: 'social-feed-app-40974',
    databaseURL: 'https://social-feed-app-40974-default-rtdb.firebaseio.com',
    storageBucket: 'social-feed-app-40974.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN7d-pUAqGBznori7mCiA2JJUa-8FTHK0',
    appId: '1:1001893276480:ios:124afd372ff0794a28a8a5',
    messagingSenderId: '1001893276480',
    projectId: 'social-feed-app-40974',
    databaseURL: 'https://social-feed-app-40974-default-rtdb.firebaseio.com',
    storageBucket: 'social-feed-app-40974.firebasestorage.app',
    iosBundleId: 'com.mossssama.socialFeed',
  );
}
